# Generated by Django 5.0.6 on 2024-06-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonkeyBarEmployee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=225)),
                ("salary", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MonkeyBarMenuItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_title", models.CharField(max_length=225)),
                ("product_description", models.TextField()),
                ("product_cost", models.IntegerField()),
                ("product_stock", models.IntegerField()),
                ("amount_sold", models.IntegerField()),
            ],
        ),
    ]
